"use strict";
exports.__esModule = true;
exports.ERROR_CODES = void 0;
// used across different AWS services
var ERROR_CODES;
(function (ERROR_CODES) {
    ERROR_CODES[ERROR_CODES["AUTHORIZATION_REQUIRES_LOGIN"] = 0] = "AUTHORIZATION_REQUIRES_LOGIN";
    ERROR_CODES[ERROR_CODES["AUTHORIZATION_REQUIRES_OWNER"] = 1] = "AUTHORIZATION_REQUIRES_OWNER";
    ERROR_CODES[ERROR_CODES["CHECK_USER_USERNAME_EXISTS"] = 2] = "CHECK_USER_USERNAME_EXISTS";
    ERROR_CODES[ERROR_CODES["CHECK_USER_EMAIL_EXISTS"] = 3] = "CHECK_USER_EMAIL_EXISTS";
    ERROR_CODES[ERROR_CODES["VERIFICATION_FAILED"] = 4] = "VERIFICATION_FAILED";
    ERROR_CODES[ERROR_CODES["VERIFICATION_ALREADY_VERIFIED"] = 5] = "VERIFICATION_ALREADY_VERIFIED";
    ERROR_CODES[ERROR_CODES["VERIFICATION_USER_DNE"] = 6] = "VERIFICATION_USER_DNE";
    ERROR_CODES[ERROR_CODES["LOGIN_FAILED"] = 7] = "LOGIN_FAILED";
    ERROR_CODES[ERROR_CODES["LOGIN_USER_DNE"] = 8] = "LOGIN_USER_DNE";
    ERROR_CODES[ERROR_CODES["GET_PASSWORD_USER_DNE"] = 9] = "GET_PASSWORD_USER_DNE";
    ERROR_CODES[ERROR_CODES["GET_PASSWORD_NOT_VERIFIED"] = 10] = "GET_PASSWORD_NOT_VERIFIED";
    ERROR_CODES[ERROR_CODES["RESET_PASSWORD_FAILED"] = 11] = "RESET_PASSWORD_FAILED";
    ERROR_CODES[ERROR_CODES["RESET_PASSWORD_USER_DNE"] = 12] = "RESET_PASSWORD_USER_DNE";
    ERROR_CODES[ERROR_CODES["RESET_PASSWORD_NOT_VERIFIED"] = 13] = "RESET_PASSWORD_NOT_VERIFIED";
    ERROR_CODES[ERROR_CODES["VOTE_REVIEW_INVALID_VALUE"] = 14] = "VOTE_REVIEW_INVALID_VALUE";
    ERROR_CODES[ERROR_CODES["VOTE_REVIEW_VOTED_ALREADY"] = 15] = "VOTE_REVIEW_VOTED_ALREADY";
    ERROR_CODES[ERROR_CODES["GET_REVIEW_INVALID_SORTING"] = 16] = "GET_REVIEW_INVALID_SORTING";
    ERROR_CODES[ERROR_CODES["GET_TIMETABLE_INVALID_ID"] = 17] = "GET_TIMETABLE_INVALID_ID";
    ERROR_CODES[ERROR_CODES["GET_TIMETABLE_EXPIRED"] = 18] = "GET_TIMETABLE_EXPIRED";
    ERROR_CODES[ERROR_CODES["INPUT_INVALID_LENGTH"] = 19] = "INPUT_INVALID_LENGTH";
    ERROR_CODES[ERROR_CODES["INPUT_INVALID_VALUE"] = 20] = "INPUT_INVALID_VALUE";
})(ERROR_CODES = exports.ERROR_CODES || (exports.ERROR_CODES = {}));
