// used across different AWS services
export enum ERROR_CODES {
  AUTHORIZATION_REQUIRES_LOGIN,
  AUTHORIZATION_REQUIRES_OWNER,

  CHECK_USER_USERNAME_EXISTS,
  CHECK_USER_EMAIL_EXISTS,

  VERIFICATION_FAILED,
  VERIFICATION_ALREADY_VERIFIED,
  VERIFICATION_USER_DNE,
  VERIFICATION_EXPIRED,

  LOGIN_FAILED,
  LOGIN_USER_DNE,

  GET_PASSWORD_USER_DNE,
  GET_PASSWORD_NOT_VERIFIED,

  RESET_PASSWORD_FAILED,
  RESET_PASSWORD_USER_DNE,
  RESET_PASSWORD_NOT_VERIFIED,

  VOTE_REVIEW_INVALID_VALUE,
  VOTE_REVIEW_VOTED_ALREADY,

  GET_REVIEW_INVALID_SORTING,

  GET_TIMETABLE_INVALID_ID,
  GET_TIMETABLE_EXPIRED,

  INPUT_INVALID_LENGTH,
  INPUT_INVALID_VALUE,
}

export enum REPORT_CODES {
  ERROR,
  FEEDBACK,
  COURSE,
  REVIEW,
}

export enum REVIEW_REPORT_TYPES {
  OTHER,
  HATE_SPEECH,
  PERSONAL_ATTACK,
  SPAM,
  MISLEADING,
}

export enum COURSE_REPORT_TYPES {
  OTHER,
  COURSE_TITLE,
  CREDITS,
  ASSESSMENTS,
  REQUIREMENTS,
  DESCRIPTION,
}

export enum VOTE_ACTIONS {
  DOWNVOTE,
  UPVOTE,
}
