export enum LoginPageMode {
  CUSIS,
  CUTOPIA_LOGIN,
  CUTOPIA_SIGNUP,
  VERIFY,
  RESET_PASSWORD,
  RESET_PASSWORD_VERIFY,
}

export enum CheckUserExistCode {
  USERNAME_EMAIL_AVAILABLE,
  USERNAME_EXIST,
  EMAIL_EXIST,
}

export enum LoginState {
  LOGGED_OUT,
  LOGGED_IN_CUSIS,
  LOGGED_IN_CUTOPIA,
}

export enum VerificationCode {
  SUCCEEDED,
  FAILED,
  ALREADY_VERIFIED,
  USER_DNE,
}

export enum LoginCode {
  SUCCEEDED,
  FAILED,
  USER_DNE,
}

export enum ErrorCardMode {
  NULL,
  ERROR,
  NOT_FOUND,
}

export enum ReviewReportMode {
  OTHER,
  HATE_SPEECH,
  PERSONAL_ATTACK,
  SPAM,
  MISLEADING,
}

export enum CourseInfoReportMode {
  OTHER,
  COURSE_TITLE,
  CREDITS,
  ASSESSMENTS,
  REQUIREMENTS,
  DESCRIPTION,
}

export enum ERROR_CODES {
  CHECK_USER_USERNAME_ALREADY_EXISTS,
  CHECK_USER_USER_EMAIL_ALREADY_EXISTS,
  VERIFICATION_FAILED,
  VERIFICATION_ALREADY_VERIFIED,
  VERIFICATION_USER_DNE,
  LOGIN_FAILED,
  LOGIN_USER_DNE,
  GET_PASSWORD_USER_DNE,
  GET_PASSWORD_NOT_VERIFIED,
  RESET_PASSWORD_FAILED,
  RESET_PASSWORD_USER_DNE,
  RESET_PASSWORD_NOT_VERIFIED,
}
