export enum LoginPageMode {
  CUSIS,
  CUTOPIA_LOGIN,
  CUTOPIA_SIGNUP,
  VERIFY,
  RESET_PASSWORD,
  RESET_PASSWORD_VERIFY,
}

export enum CheckUserExistCode {
  USERNAME_EMAIL_AVAILABLE,
  USERNAME_EXIST,
  EMAIL_EXIST,
}

export enum LoginState {
  INIT,
  LOGGED_OUT,
  LOGGED_IN,
}

export enum VerificationCode {
  SUCCEEDED,
  FAILED,
  ALREADY_VERIFIED,
  USER_DNE,
}

export enum LoginCode {
  SUCCEEDED,
  FAILED,
  USER_DNE,
}

export enum ErrorCardMode {
  NULL,
  ERROR,
  NOT_FOUND,
}

export enum ReportCategory {
  ERROR,
  FEEDBACK,
  COURSE,
  REVIEW,
}

export enum ReviewReportMode {
  OTHER,
  HATE_SPEECH,
  PERSONAL_ATTACK,
  SPAM,
  MISLEADING,
}

export enum CourseInfoReportMode {
  OTHER,
  COURSE_TITLE,
  CREDITS,
  ASSESSMENTS,
  REQUIREMENTS,
  DESCRIPTION,
}

export enum ERROR_CODES {
  AUTHORIZATION_REQUIRES_LOGIN,
  AUTHORIZATION_REQUIRES_OWNER,
  CREATE_USER_INVALID_EMAIL,
  CREATE_USER_USERNAME_EXISTS,
  CREATE_USER_EMAIL_EXISTS,
  VERIFICATION_FAILED,
  VERIFICATION_ALREADY_VERIFIED,
  VERIFICATION_USER_DNE,
  LOGIN_FAILED,
  LOGIN_USER_DNE,
  GET_PASSWORD_USER_DNE,
  GET_PASSWORD_NOT_VERIFIED,
  RESET_PASSWORD_FAILED,
  RESET_PASSWORD_USER_DNE,
  RESET_PASSWORD_NOT_VERIFIED,
  CREATE_REVIEW_ALREADY_CREATED,
  VOTE_REVIEW_INVALID_VALUE,
  VOTE_REVIEW_VOTED_ALREADY,
  GET_REVIEW_INVALID_SORTING,
  GET_TIMETABLE_INVALID_ID,
  GET_TIMETABLE_EXPIRED,
  INPUT_INVALID_LENGTH,
  INPUT_INVALID_VALUE,
}
